import { flattenObjectToKeyValuePairs } from "../flatten-object-to-key-value-pairs"

describe("flattenObjectToKeyValuePairs", function () {
  it("should return only the properties path of the properties that are set to true", function () {
    const cart = {
      id: "cart_id",
      customer: {
        id: "cus_id",
        groups: [
          { id: "group_1", name: "test" },
          { id: "group_2", name: "test 2" },
        ],
      },
      items: [
        {
          product_id: "product-1",
          product: { id: "product-1" },
        },
        {
          product_id: "product-2",
          product: {
            id: "product-2",
            something: [
              {
                id: "test",
              },
            ],
          },
        },
      ],
    }

    const keyValueParis = flattenObjectToKeyValuePairs(cart)
    expect(keyValueParis).toEqual({
      id: "cart_id",
      "customer.id": "cus_id",
      "customer.groups.id": ["group_1", "group_2"],
      "customer.groups.name": ["test", "test 2"],
      "items.product_id": ["product-1", "product-2"],
      "items.product.id": ["product-1", "product-2"],
      "items.product.something.id": ["test"],
    })
  })

  it("should handle complex nested objects", function () {
    const cart = {
      id: "cart_01JRDH08QD8CZ0KJDVE410KM1J",
      currency_code: "usd",
      email: "tony@stark-industries.com",
      region_id: "reg_01JRDH08ENY3276P6133BVXGWJ",
      created_at: "2025-04-09T14:59:24.526Z",
      updated_at: "2025-04-09T14:59:24.526Z",
      completed_at: null,
      total: 1500,
      subtotal: 1428.5714285714287,
      tax_total: 71.42857142857143,
      discount_total: 0,
      discount_subtotal: 0,
      discount_tax_total: 0,
      original_total: 1500,
      original_tax_total: 71.42857142857143,
      item_total: 1500,
      item_subtotal: 1428.5714285714287,
      item_tax_total: 71.42857142857143,
      original_item_total: 1500,
      original_item_subtotal: 1428.5714285714287,
      original_item_tax_total: 71.42857142857143,
      shipping_total: 0,
      shipping_subtotal: 0,
      shipping_tax_total: 0,
      original_shipping_tax_total: 0,
      original_shipping_subtotal: 0,
      original_shipping_total: 0,
      credit_line_subtotal: 0,
      credit_line_tax_total: 0,
      credit_line_total: 0,
      metadata: null,
      sales_channel_id: "sc_01JRDH08KWX1AR5SB0A3THWWQQ",
      shipping_address_id: "caaddr_01JRDH08QDXHV9SJXKHT04TXK0",
      customer_id: "cus_01JRDH08ATYB5AMFEZDTWCQWNK",
      items: [
        {
          id: "cali_01JRDH08QDQH3CB1DE4S79HREC",
          thumbnail: null,
          variant_id: "variant_01JRDH08GJCZQB4GZCDDTYMD1V",
          product_id: "prod_01JRDH08FPZ6QBZQ096B310RM7",
          product_type_id: null,
          product_title: "Medusa T-Shirt",
          product_description: null,
          product_subtitle: null,
          product_type: null,
          product_collection: null,
          product_handle: "t-shirt",
          variant_sku: "SHIRT-S-BLACK",
          variant_barcode: null,
          variant_title: "S / Black",
          requires_shipping: true,
          metadata: {},
          created_at: "2025-04-09T14:59:24.526Z",
          updated_at: "2025-04-09T14:59:24.526Z",
          title: "S / Black",
          quantity: 1,
          unit_price: 1500,
          compare_at_unit_price: null,
          is_tax_inclusive: true,
          tax_lines: [
            {
              id: "calitxl_01JRDH08RJEQ4WXXDTJYWV7B4M",
              description: "CA Default Rate",
              code: "CADEFAULT",
              rate: 5,
              provider_id: "system",
            },
          ],
          adjustments: [],
          product: {
            id: "prod_01JRDH08FPZ6QBZQ096B310RM7",
            collection_id: null,
            type_id: null,
            categories: [],
            tags: [],
          },
        },
      ],
      shipping_methods: [],
      shipping_address: {
        id: "caaddr_01JRDH08QDXHV9SJXKHT04TXK0",
        first_name: null,
        last_name: null,
        company: null,
        address_1: "test address 1",
        address_2: "test address 2",
        city: "SF",
        postal_code: "94016",
        country_code: "US",
        province: "CA",
        phone: null,
      },
      billing_address: null,
      credit_lines: [],
      customer: {
        id: "cus_01JRDH08ATYB5AMFEZDTWCQWNK",
        email: "tony@stark-industries.com",
        groups: [],
      },
      region: {
        id: "reg_01JRDH08ENY3276P6133BVXGWJ",
        name: "US",
        currency_code: "usd",
        automatic_taxes: true,
        countries: [
          {
            iso_2: "us",
            iso_3: "usa",
            num_code: "840",
            name: "UNITED STATES",
            display_name: "United States",
            region_id: "reg_01JRDH08ENY3276P6133BVXGWJ",
            metadata: null,
            created_at: "2025-04-09T14:59:20.275Z",
            updated_at: "2025-04-09T14:59:24.250Z",
            deleted_at: null,
          },
        ],
      },
      promotions: [],
    }

    const keyValueParis = flattenObjectToKeyValuePairs(cart)
    expect(keyValueParis).toEqual({
      id: "cart_01JRDH08QD8CZ0KJDVE410KM1J",
      currency_code: "usd",
      email: "tony@stark-industries.com",
      region_id: "reg_01JRDH08ENY3276P6133BVXGWJ",
      created_at: "2025-04-09T14:59:24.526Z",
      updated_at: "2025-04-09T14:59:24.526Z",
      total: 1500,
      subtotal: 1428.5714285714287,
      tax_total: 71.42857142857143,
      discount_total: 0,
      discount_subtotal: 0,
      discount_tax_total: 0,
      original_total: 1500,
      original_tax_total: 71.42857142857143,
      item_total: 1500,
      "items.adjustments": [],
      item_subtotal: 1428.5714285714287,
      item_tax_total: 71.42857142857143,
      original_item_total: 1500,
      original_item_subtotal: 1428.5714285714287,
      original_item_tax_total: 71.42857142857143,
      shipping_total: 0,
      shipping_subtotal: 0,
      shipping_tax_total: 0,
      original_shipping_tax_total: 0,
      original_shipping_subtotal: 0,
      original_shipping_total: 0,
      credit_line_subtotal: 0,
      credit_line_tax_total: 0,
      credit_line_total: 0,
      sales_channel_id: "sc_01JRDH08KWX1AR5SB0A3THWWQQ",
      shipping_address_id: "caaddr_01JRDH08QDXHV9SJXKHT04TXK0",
      customer_id: "cus_01JRDH08ATYB5AMFEZDTWCQWNK",
      "items.id": ["cali_01JRDH08QDQH3CB1DE4S79HREC"],
      "items.variant_id": ["variant_01JRDH08GJCZQB4GZCDDTYMD1V"],
      "items.product_id": ["prod_01JRDH08FPZ6QBZQ096B310RM7"],
      "items.product_title": ["Medusa T-Shirt"],
      "items.product_handle": ["t-shirt"],
      "items.variant_sku": ["SHIRT-S-BLACK"],
      "items.variant_title": ["S / Black"],
      "items.requires_shipping": [true],
      "items.created_at": ["2025-04-09T14:59:24.526Z"],
      "items.updated_at": ["2025-04-09T14:59:24.526Z"],
      "items.title": ["S / Black"],
      "items.quantity": [1],
      "items.unit_price": [1500],
      "items.is_tax_inclusive": [true],
      "items.tax_lines.id": ["calitxl_01JRDH08RJEQ4WXXDTJYWV7B4M"],
      "items.tax_lines.description": ["CA Default Rate"],
      "items.tax_lines.code": ["CADEFAULT"],
      "items.tax_lines.rate": [5],
      "items.tax_lines.provider_id": ["system"],
      "items.product.id": ["prod_01JRDH08FPZ6QBZQ096B310RM7"],
      "items.product.categories": [],
      "items.product.tags": [],
      shipping_methods: [],
      "shipping_address.id": "caaddr_01JRDH08QDXHV9SJXKHT04TXK0",
      "shipping_address.address_1": "test address 1",
      "shipping_address.address_2": "test address 2",
      "shipping_address.city": "SF",
      "shipping_address.postal_code": "94016",
      "shipping_address.country_code": "US",
      "shipping_address.province": "CA",
      credit_lines: [],
      "customer.id": "cus_01JRDH08ATYB5AMFEZDTWCQWNK",
      "customer.email": "tony@stark-industries.com",
      "customer.groups": [],
      "region.id": "reg_01JRDH08ENY3276P6133BVXGWJ",
      "region.name": "US",
      "region.currency_code": "usd",
      "region.automatic_taxes": true,
      "region.countries.iso_2": ["us"],
      "region.countries.iso_3": ["usa"],
      "region.countries.num_code": ["840"],
      "region.countries.name": ["UNITED STATES"],
      "region.countries.display_name": ["United States"],
      "region.countries.region_id": ["reg_01JRDH08ENY3276P6133BVXGWJ"],
      "region.countries.created_at": ["2025-04-09T14:59:20.275Z"],
      "region.countries.updated_at": ["2025-04-09T14:59:24.250Z"],
      promotions: [],
    })
  })
})
